# Generated by Django 3.0.7 on 2020-06-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_app', '0002_auto_20200621_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='dessignation_id',
            new_name='designation_id',
        ),
    ]
